name: day_butler
description: "Birthday Butler - Never miss a special moment."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  get: ^4.7.2
  styled_widget: ^0.4.1
  sqflite: ^2.4.2
  path: ^1.9.1
  flutter_inappwebview: ^6.1.5
  intl: ^0.20.2
  fluttertoast: ^8.2.5
  shared_preferences: ^2.3.0
  url_launcher: ^6.3.0
  flutter_timezone: ^4.1.0
  image_picker: ^1.1.2
  dio: ^5.4.3+1
  path_provider: ^2.1.5
  flutter_local_notifications: ^17.0.0
  package_info_plus: ^8.0.0
  timezone: ^0.9.0
  permission_handler: ^11.3.0
  flutter_slidable: ^3.1.1
  flutter_launcher_icons: ^0.14.4
  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # flutter pub run flutter_launcher_icons:main
flutter_launcher_icons:
  image_path: "assets/star.png"
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/star.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/tabs/
